### ISSUE TITLE
CSS Modules Support

### ISSUE THREAD

**Issue by katywings** [marbemac/ssrx#22]
First and foremost I want to say, ssrx is impressive, thank you for the amazing work! It ticks a lot of boxes for me with its focus on solving one thing, that is building the client/server glue for ssr. I definitely will continue experimenting with ssrx. 

During a quick try with the `solid-router-simple` I noticed that css modules don't seem to be supported. The style tags that are getting rendered in `vite dev` for css modules, have `undefined` as content. 

I would've also tested this in the prod build, but the prod build seems to be broken at the moment ':), the `build.server` script deletes the client assets and it also does not even create a `dist/server.js`.

**Comment by marbemac** [comment]
Thanks @katywings! I'll take a look this week.

**Comment by marbemac** [comment]
Alrighty - https://github.com/marbemac/ssrx/releases/tag/%40ssrx%2Fvite%400.5.0 should fix the build issue, and also adds support for css modules. LMK how it works for you!

**Comment by marbemac** [comment]
BTW I'm also working on updating things to support solid-router v0.10, which introduced a number of breaking changes. Will hopefully push that soon.

**Comment by katywings** [comment]
Good evening Marc

Wow, ty for the fixes <3! So far it works greatly on the old router, I will continue testing it :). 

I actually also initially tried it with the newest solid-router version and a couple of router v0.10 compat changes in the example code, but that didn't work so easily - inconsistent suspense and css module styles (sometimes empty pages or missing styles), you probably already know what I am talking about ;).

**Comment by marbemac** [comment]
Hi @katywings - I've just released some new versions, and updated the solid example. Please let me know if it works as you're expecting when you have a chance!

**Comment by katywings** [comment]
The new changes are superb, awesome work :)!

- Inconsistencies with suspense and css modules seem to be indeed gone 💪
- Even a quick [lxsmnsyc/thaler](https://github.com/lxsmnsyc/thaler) integration worked like a charm so far
- Not sure if this came with the new changes, but if you start the vite dev server and open localhost a bit too early in the browser, the server instantly crashes
- Unrelated to this issue, but solid router just released a new version 0.11.0 that broke the server 🫠 (`Error: Cannot find cache context`)

**Comment by marbemac** [comment]
Great!

> Even a quick [lxsmnsyc/thaler](https://github.com/lxsmnsyc/thaler) integration worked like a charm so far

Nice - curious, what are you after w thaler?

> Not sure if this came with the new changes, but if you start the vite dev server and open localhost a bit too early in the browser, the server instantly crashes

Hmm, I'll see if anything can be done about this.

> Unrelated to this issue, but solid router just released a new version 0.11.0 that broke the server 

Yeahhh, seems like the new solid-router expects any code that leverages the new `cache()` to be run in an async context via `import { provideRequestEvent } from "solid-js/web/storage";` - @ryansolid is this correct? Can't find any mentions of it in the docs though - is `provideRequestEvent` a private API or is it OK to use?

If ok to use I could incorporate that into the ssrx solid plugin easily.. the "simple" example becomes a little less simple, but not by much.

**Comment by katywings** [comment]
@marbemac The vite dev works greatly now, on all latest versions! The build on the other hand currently doesn't work, I think because the changes from 82510ab4d812f69413fe1500181d48a918a4558e only were released in the `@ssrx/renderer` but not the other packages such as `@ssrx/solid`.

> Nice - curious, what are you after w thaler?

For me `ssrx` feels like a more minimalistic, less "biased / fully-featured" ssr formula compared to say `vike` or `solid-start`. This not only makes it as a great example and playground to learn how other meta frameworks join their pieces together, but also as a great foundation for projects which wanna trade away built-in features for more flexibility. `thaler` and `[telefunc](https://telefunc.com/)` both are meta framework independent solutions for the implementation of decoupled server functions, which perfectly fit into the `ssrx` thinking model regarding "choose your own stack" :).

**Comment by marbemac** [comment]
> The build on the other hand currently doesn't work, I think because the changes from https://github.com/marbemac/ssrx/commit/82510ab4d812f69413fe1500181d48a918a4558e only were released in the @ssrx/renderer but not the other packages such as @ssrx/solid.

That's exactly why - the examples worked locally because all the packages are locally linked 🤦‍♂️. Should be fixed in the latest release!

> For me ssrx feels like a more minimalistic, less "biased / fully-featured" ssr formula compared to say vike or solid-start. This not only makes it as a great example and playground to learn how other meta frameworks join their pieces together

That's exactly what I was after, I'm glad you're enjoying it! It's been a great learning experience for me as well.

> thaler and [telefunc](https://telefunc.com/) both are meta framework independent solutions for the implementation of decoupled server functions

Yeah they're very cool, let me know how it works out for you! If the code is public, I'd love to see it. 

What I've landed on for "decoupled server functions", that feels a bit less magical than thaler, is just tanstack query + trpc. Type-safe, trpc supports middleware and all the other goodies you'd expect, isomorphic on the client and server (on the server is just calls the trpc functions directly vs over http on the client). The caching/invalidation approach of tanstack query works nicely as well. Lastly, super easy to add a new function - just add it to the trpc router and it's immediately available on the query client for use. The `react-router-kitchen-sink` example shows all of this working together.

**Comment by katywings** [comment]
Yupp, trpc is indeed very nice :). In my case, the main reason for thaler/telefunc or other types of server functions is "plug-and-play". I am working on a oss cms that features visual building blocks, which can be very easily integrated by developers. My vision is that developers can share these building blocks with other developers without having to manually wire up server logic. The goal is that such blocks can even include basic server behaviour via server functions.
